apiVersion: kuma.io/v1alpha1
kind: TrafficPermission
mesh: default
metadata:
  name: db.mesh-demo-prod.svc.5432
spec:
  sources:
    - match:
        kuma.io/service: result_mesh-demo-prod_svc_5001
    - match:
        kuma.io/service: worker_mesh-demo-prod_svc
  destinations:
    - match:
        kuma.io/service: db_mesh-demo-prod_svc_5432
