apiVersion: kuma.io/v1alpha1
kind: TrafficRoute
mesh: default
metadata:
  name: redis.mesh-demo.svc.6379
spec:
  sources:
    - match:
        kuma.io/service: vote_mesh-demo_svc_5000
    - match:
        kuma.io/service: worker_mesh-demo_svc
  conf:
    loadBalancer:
      roundRobin: {}
    destination:
      kuma.io/service: redis_mesh-demo_svc_6379
  destinations:
  - match:
      kuma.io/service: redis_mesh-demo_svc_6379
