apiVersion: kuma.io/v1alpha1
kind: TrafficPermission
mesh: default
metadata:
  name: pgsql-eli-db-dev.postgres.database.azure.com.5432.ext
spec:
  sources:
    - match:
        kuma.io/service: result_mesh-demo_svc_5001
  destinations:
    - match:
        kuma.io/service: pgsql-eli-db-dev-postgres-database-azure-com-5432
      