kind: TrafficPermission
apiVersion: kuma.io/v1alpha1
metadata:
  name: allow-all-default
mesh: default
spec:
  sources:
    - match:
        kuma.io/service: '*'
  destinations:
    - match:
        kuma.io/service: '*'